### PR TITLE
Cypress

### PR DESCRIPTION
**Pull request by VasaviGannena**
Pull request add cypress for test. They is no test yet.

### CODE REVIEW

**Comment by klubiniecki** [comment]
Hey team! Why would we want to have this code in develop branch? Or maybe different question - what’s the purpose of develop branch in our project? Thanks!

**Comment by k7n4n5t3w4rt** [comment]
@klubiniecki We were practising a git-flow branching strategy, hence `develop` for integrating work done on feature branches. Since `develop` hasn't been used it seemed like a way to keep the mob programming practice safely out of the way while still allowing it to be integrated at some point if the work seems useful.

This pull request is just for adding Cypress to the codebase. Something worth considering if we want to have some functional testing on the project. Obviously not the only choice for that but it's potentially a good choice.

**Comment by klubiniecki** [comment]
> @klubiniecki We were practising a git-flow branching strategy, hence `develop` for integrating work done on feature branches. Since `develop` hasn't been used it seemed like a way to keep the mob programming practice safely out of the way while still allowing it to be integrated at some point if the work seems useful.
> 
> This pull request is just for adding Cypress to the codebase. Something worth considering if we want to have some functional testing on the project. Obviously not the only choice for that but it's potentially a good choice.

Thanks for quick response @k7n4n5t3w4rt! If we keep `develop` as a learning branch to play around that makes sense. I'm used to `develop` or `staging` branch being a mirror of `main` branch as much as possible. 

My preference would be to keep learning in learning branches (and `cypress` is a great, descriptive name to point people to if they want to find examples). Having said that, I'm all up for adding cypress and one integration/acceptance test that covers already written code to `main/master` 👍

**Comment by hqtan** [comment]
Hi @VasaviGannena ,

imho, the only files that should be committed in this PR is `package.json` and `package-lock.json`

Do we need to commit all the contents of `cypress/` ?

my reason(s) why we should keep `cypress/` out of our codebase:
- there is nothing in `cypress/` that is specific to our project, so why keep it?
- we currently really only need cypress when testing in our development environment, and we get all the files in `cypress/` generated when we install the cypress npm package, so there's no need to commit them.
- ask yourself this questrion: do we need anything in `cypress/` to run our project? if the answer is no, we should omit it. The only exceptions are tests, but there are no tests that are specific to our project in `cypress/` afaict...

let's keep our repo tidy, and commit things that are only necessary :bow:

**Comment by VasaviGannena** [comment]
close my PR request

**Pull request closed without merging**
